name: nsysu_ap
description: NSYSU AP

version: 0.3.3+303

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ap_common: 0.4.0
  #   path: ../../GitHub-NKUST-ITC/ap_common
  ap_common_firebase:
    git:
      url: https://github.com/abc873693/ap_common_firebase
      ref: v0.2.0
  #     path: ../ap_common_firebase

  #official plugin
  http: 0.12.2
  html: ^0.14.0+3
  path_provider: 1.6.11
  webview_flutter: 0.3.22+1

  #third party plugin
  encrypt: 4.0.1
  sprintf: ^4.0.2
  crypto: ^2.1.4
  big5: 0.0.4
  printing: 3.5.0
  dio: 3.0.10
  dio_cookie_manager: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
