name: nsysu_ap
description: NSYSU AP

version: 0.5.1+501

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ap_common: 0.8.0-beta.1
  #   path: ../../GitHub-NKUST-ITC/ap_common
  ap_common_firebase:
    git:
      url: https://github.com/abc873693/ap_common_firebase
      ref: v0.3.1
  #     path: ../ap_common_firebase
  ap_common_plugin:
    git:
      url: https://github.com/abc873693/ap_common_plugin
      ref: v0.0.5
  #    path: ../ap_common_plugin

  #official plugin
  http: 0.12.2
  html: ^0.14.0+3
  path_provider: 1.6.18
  webview_flutter: 1.0.0

  #third party plugin
  encrypt: 4.0.3
  sprintf: ^4.0.2
  crypto: ^2.1.5
  big5: 0.0.4
  printing: 3.6.1
  dio: 3.0.10
  dio_cookie_manager: 1.0.0
  image: ^2.1.4
  tflite: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/labels.txt
    - assets/model.tflite
