name: nsysu_ap
description: NSYSU AP

version: 0.6.0+600

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ap_common: 0.13.2
  #   path: ../../GitHub-NKUST-ITC/ap_common
  ap_common_firebase: 0.6.0-dev.2
  #   path: ../ap_common_firebase
  ap_common_plugin: 0.1.5
#     path: ../ap_common_plugin

  #official plugin
  http: 0.12.2
  html: ^0.14.0+4
  webview_flutter: ^1.0.7

  #third party plugin
  encrypt: 4.1.0
  sprintf: ^5.0.0
  crypto: ^2.1.5
  big5: 0.0.4
  dio: 3.0.10
  dio_cookie_manager: 1.0.0
  extended_image: 1.3.1-dev

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
